apiVersion: v1
kind: Secret
metadata:
  name: openagi-builder-secrets
type: Opaque
data:
  # These are base64 encoded values
  # In production, use proper secret management
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvb3BlbmFnaV9idWlsZGVy
  nextauth-secret: c3VwZXJzZWNyZXRuZXh0YXV0aHNlY3JldA==
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  github-client-id: eW91cl9naXRodWJfY2xpZW50X2lk
  github-client-secret: eW91cl9naXRodWJfY2xpZW50X3NlY3JldA==
  facebook-client-id: eW91cl9mYWNlYm9va19jbGllbnRfaWQ=
  facebook-client-secret: eW91cl9mYWNlYm9va19jbGllbnRfc2VjcmV0

